spring.application.name=text-to-speech

server.port=8080

#deepgram.api.key=${a3512b90480dc8c08477ba784d7df4c9fa812df5}
#deepgram.api.url=https://api.deepgram.com/v1/speak
#deepgram.api.model=aura-2-thalia-en


deepgram.api.key=${DEEPGRAM_API_KEY}
deepgram.api.url=https://api.deepgram.com/v1/speak
#deepgram.api.model=aura-2-thalia-en

sarvam.api.key={API}
sarvam.api.url=https://api.sarvam.ai/text-to-speech


# google.cloud.project-id=YOUR_GOOGLE_CLOUD_PROJECT_ID