spring.application.name=text-to-speech

server.port=8080




deepgram.api.key=${DEEPGRAM_API_KEY}
deepgram.api.url=https://api.deepgram.com/v1/speak
#deepgram.api.model=aura-2-thalia-en

sarvam.api.key={API}
sarvam.api.url=https://api.sarvam.ai/text-to-speech

AWS.REGION=ap-south-1
aws.access-key-id=************
aws.secret-access-key=************
